// Generated by scripts/email/sync-tokens.mjs from app/tokens.css. Do not edit by hand:
// change the site tokens, then run `node scripts/email/sync-tokens.mjs`.
// Colours are solid hex (rgba tokens blended over the page background) because email clients
// do not support CSS variables and Outlook ignores rgba.
export const tokens = {
  "light": {
    "bg": "#ffffff",
    "bgSubtle": "#f7f7f5",
    "bgRaised": "#ffffff",
    "text": "#37352f",
    "textSecondary": "#6f6e69",
    "textTertiary": "#a5a4a1",
    "border": "#ededec",
    "borderStrong": "#dfdfde",
    "accent": "#1a6fd0",
    "accentHover": "#155db0",
    "accentText": "#1a6fd0",
    "accentSoft": "#e8f1fa",
    "onAccent": "#ffffff",
    "logoTile": "#37352f",
    "logoGlyph": "#ffffff",
    "logoDot": "#5aa5e6",
    "tagGray": "#6b6a66",
    "tagGrayBg": "#f1f1ef",
    "tagBlue": "#2b6f99",
    "tagBlueBg": "#e7f3f8",
    "tagPurple": "#7c4fa3",
    "tagPurpleBg": "#f4f0f7",
    "tagOrange": "#a35508",
    "tagOrangeBg": "#fbecdd",
    "tagYellow": "#8f6514",
    "tagYellowBg": "#fbf3db",
    "tagGreen": "#3a7154",
    "tagGreenBg": "#edf3ec",
    "tagRed": "#c13e39",
    "tagRedBg": "#fdebec"
  },
  "dark": {
    "bg": "#191919",
    "bgSubtle": "#202020",
    "bgRaised": "#252525",
    "text": "#dfdfdf",
    "textSecondary": "#9a9a9a",
    "textTertiary": "#707070",
    "border": "#2b2b2b",
    "borderStrong": "#393939",
    "accent": "#1a6fd0",
    "accentHover": "#2577d6",
    "accentText": "#5aa5e6",
    "accentSoft": "#232f3a",
    "onAccent": "#ffffff",
    "logoTile": "#dfdfde",
    "logoGlyph": "#191919",
    "logoDot": "#1a6fd0",
    "tagGray": "#a5a5a5",
    "tagGrayBg": "#2f2f2f",
    "tagBlue": "#6cb3e0",
    "tagBlueBg": "#143a4e",
    "tagPurple": "#b896e6",
    "tagPurpleBg": "#3c2d49",
    "tagOrange": "#ffa95c",
    "tagOrangeBg": "#5c3b23",
    "tagYellow": "#f2cf5b",
    "tagYellowBg": "#564328",
    "tagGreen": "#6fc2a6",
    "tagGreenBg": "#243d30",
    "tagRed": "#ff8a80",
    "tagRedBg": "#522e2a"
  },
  "font": {
    "sans": "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, 'Apple Color Emoji', Arial, sans-serif, 'Segoe UI Emoji', 'Segoe UI Symbol'",
    "mono": "'iA Writer Mono', Nitti, ui-monospace, SFMono-Regular, Menlo, Consolas, Courier, monospace",
    "features": "'lnum' 1, 'locl' 0"
  },
  "size": {
    "h1": 40,
    "h2": 30,
    "h3": 24,
    "h4": 20,
    "lg": 18,
    "base": 16,
    "sm": 14,
    "xs": 12
  },
  "leading": {
    "tight": 1.2,
    "snug": 1.4,
    "body": 1.6
  },
  "tracking": {
    "title": "-0.025em",
    "heading": "-0.02em"
  },
  "space": {
    "1": 4,
    "2": 8,
    "3": 12,
    "4": 16,
    "5": 24,
    "6": 32,
    "7": 48,
    "8": 64
  },
  "radius": {
    "xs": 3,
    "sm": 6,
    "md": 10,
    "lg": 14
  }
} as const;

export type Palette = typeof tokens.light;
