// Reads app/tokens.css and writes lib/email/tokens.ts: the same design tokens as the site,
// as solid hex colours that email clients understand (Outlook ignores rgba and CSS variables).
//
//   node scripts/email/sync-tokens.mjs          writes the file
//   node scripts/email/sync-tokens.mjs --check  fails if the file is out of date
import fs from "node:fs";

const css = fs.readFileSync(new URL("../../app/tokens.css", import.meta.url), "utf8");
const out = new URL("../../lib/email/tokens.ts", import.meta.url);

function block(re) {
  const m = css.match(re);
  if (!m) throw new Error("tokens.css: block not found " + re);
  const vars = {};
  for (const [, k, v] of m[1].matchAll(/--([\w-]+):\s*([^;]+);/g)) vars[k] = v.trim();
  return vars;
}

const light = block(/^:root \{([\s\S]*?)^\}/m);
const dark = { ...light, ...block(/@media \(prefers-color-scheme: dark\) \{\s*:root:not\(\[data-theme="light"\]\) \{([\s\S]*?)\}/) };

function rgb(v) {
  const hex = v.match(/^#([0-9a-f]{6})$/i);
  if (hex) return [0, 2, 4].map((i) => parseInt(hex[1].slice(i, i + 2), 16)).concat(1);
  const fn = v.match(/^rgba?\(([^)]+)\)$/);
  if (fn) {
    const p = fn[1].split(",").map((s) => parseFloat(s));
    return [p[0], p[1], p[2], p[3] ?? 1];
  }
  throw new Error("colour not understood: " + v);
}

// rgba over a background → one solid colour, as it looks on screen.
function solid(v, over) {
  const [r, g, b, a] = rgb(v);
  const [br, bg, bb] = rgb(over);
  const mix = (c, d) => Math.round(c * a + d * (1 - a)).toString(16).padStart(2, "0");
  return `#${mix(r, br)}${mix(g, bg)}${mix(b, bb)}`;
}

const colourKeys = [
  "bg", "bg-subtle", "bg-raised", "text", "text-secondary", "text-tertiary", "border", "border-strong",
  "accent", "accent-hover", "accent-text", "accent-soft", "on-accent", "logo-tile", "logo-glyph", "logo-dot",
  ...["gray", "blue", "purple", "orange", "yellow", "green", "red"].flatMap((c) => [`tag-${c}`, `tag-${c}-bg`]),
];

function palette(vars) {
  const o = {};
  for (const k of colourKeys) o[k.replace(/-(\w)/g, (_, c) => c.toUpperCase())] = solid(vars[k], vars.bg);
  return o;
}

const px = (v) => parseInt(v, 10);
const tokens = {
  light: palette(light),
  dark: palette(dark),
  font: {
    sans: light["font-sans"].replace(/"/g, "'"),
    mono: light["font-mono"].replace(/"/g, "'"),
    features: light["font-features"].replace(/"/g, "'"),
  },
  size: {
    h1: px(light["text-h1"]), h2: px(light["text-h2"]), h3: px(light["text-h3"]), h4: px(light["text-h4"]),
    lg: px(light["text-lg"]), base: px(light["text-base"]), sm: px(light["text-sm"]), xs: px(light["text-xs"]),
  },
  leading: { tight: +light["leading-tight"], snug: +light["leading-snug"], body: +light["leading-body"] },
  tracking: { title: light["tracking-title"], heading: light["tracking-heading"] },
  space: Object.fromEntries([1, 2, 3, 4, 5, 6, 7, 8].map((n) => [n, px(light[`space-${n}`])])),
  radius: { xs: px(light["radius-xs"]), sm: px(light["radius-sm"]), md: px(light["radius-md"]), lg: px(light["radius-lg"]) },
};

const body = `// Generated by scripts/email/sync-tokens.mjs from app/tokens.css. Do not edit by hand:
// change the site tokens, then run \`node scripts/email/sync-tokens.mjs\`.
// Colours are solid hex (rgba tokens blended over the page background) because email clients
// do not support CSS variables and Outlook ignores rgba.
export const tokens = ${JSON.stringify(tokens, null, 2)} as const;

export type Palette = typeof tokens.light;
`;

if (process.argv.includes("--check")) {
  const current = fs.existsSync(out) ? fs.readFileSync(out, "utf8") : "";
  if (current !== body) {
    console.error("lib/email/tokens.ts is out of date: run node scripts/email/sync-tokens.mjs");
    process.exit(1);
  }
  console.log("lib/email/tokens.ts matches app/tokens.css");
} else {
  fs.writeFileSync(out, body);
  console.log("wrote lib/email/tokens.ts");
}
